# @name hello_world

@base_url = http://localhost:3333

POST {{base_url}}/restaurants
Content-Type: application/json

{
  "restaurantName": "Pizza Heaven",
  "name": "John Doe",
  "email": "johndoe@example.com",
  "phone": "+1234567890",
}